version: '3.8'

services:
  # Application FastAPI
  api:
    build:
      context: . # Le contexte de build est le répertoire courant
      dockerfile: api.Dockerfile # Utilise le Dockerfile spécifique à l'API
    ports:
      - "8000:8000" # Mappe le port 8000 de l'hôte au port 8000 du conteneur
    env_file:
      - .env # Charge les variables d'environnement depuis le fichier .env (contient REDIS_URL pour Upstash)
    networks:
      - app_network

  # Celery Worker
  worker:
    build:
      context: . # Le contexte de build est le répertoire courant
      dockerfile: worker.Dockerfile # Utilise le Dockerfile spécifique au worker
    env_file:
      - .env # Charge les variables d'environnement depuis le fichier .env (contient REDIS_URL pour Upstash)
    depends_on:
      - api # Dépend de l'API pour une cohérence logique
    networks:
      - app_network

networks:
  app_network: # Définit un réseau personnalisé pour une meilleure isolation et un nommage clair
    driver: bridge
